name: 'pnpm-workspace-release-action'
description: 'automated releases for pnpm based on conventional commits'
author: Jason

inputs:
  token:
    description: GitHub token for creating and grooming release PRs, defaults to using secrets.GITHUB_TOKEN
    required: false
    default: ${{ github.token }}

  preid:
    description: Identifier to be used to prefix prerelease version increments
    required: false

  latest:
    description: Whether the release should be set as the latest release
    required: false
    default: false

runs:
  using: 'node20'
  main: 'action/index.js'
