name: 'pnpm-workspace-release-action'
description: 'automated releases for pnpm based on conventional commits'
author: Jason
inputs:
  token:
    description: 'GitHub token for creating and grooming release PRs, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
